* Fixed a bug in the graph_on_control invocation where the title bar (+10)   was not taken care of. * Fixed window drawing to look a bit more as in the original games * Removed background drawing from Display() for the time being. * Killed a bug in the call opcode. This bug was responsible for the   stack overflows. * Made Said() return 0 always. This fixes the "First program bug" problem   in the QG1 main menu. * Changed struct timeval to GTimeVal. Now I get dozens of warnings. Oh joy.
Results:
+ It's now possible to move the hero around the QfG1 world. Clipping and
  priority checking still have problems, though.
+ Similar status for LSL3.


Todo:
- SQ3 doesn't get its sound cues correctly. 95% chance of being a bug in
  the null sound server.
- QG1 halts for unknown reasons during combat.
- Priority and Control checks are not perfect yet.
- The character config screen in QG1 is non-functional.
- QG2 halts because of an invalid DoSound(). Maybe DoSound() works differently
  in SCI01.
- Entering a command (and failing to parse it) creates a big priority 15
  (maybe even 255) block. Needs investigation.
- Oh, and Random() doesn't really work randomly, as it seems. Not sure if
  I forgot to initialize the random number generator, or if I mis-implemented
  it.

Now each bug needs to be tracked down and eliminated separately. This will
be at least as much work as implementing the functions (and this hasn't
been completed either).
Still, it's possible to walk around now. If I wasn't too tired to think
straight, I'd probably be happy.


 - Christoph

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1511,7 +1511,7 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-  min_glib_version=0.9.7
+  min_glib_version=1.2.0
   echo $ac_n "checking for GLIB - version >= $min_glib_version""... $ac_c" 1>&6
 echo "configure:1517: checking for GLIB - version >= $min_glib_version" >&5
   no_glib=""
@@ -1695,7 +1695,7 @@ rm -f conftest*
      GLIB_LIBS=""
      
 #if glib was't found
-		{ echo "configure: error: You must install glib to compile this package!" 1>&2; exit 1; }
+		{ echo "configure: error: You must install a recent version of glib to compile this package!" 1>&2; exit 1; }
 	
   fi
   
